### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by rootdarkarchon** [PrincessRTFM/XIVComboPlugin#41]
![image](https://user-images.githubusercontent.com/21534284/164060300-52e2be3f-d442-4f9f-8542-2a7bf2eff71e.png)

Getting this issue trying to update to the latest version.

**Comment by Evolutious** [comment]
I think this may be a Dalamud issue. I am getting the same error, but since i previously had it loaded and configured, my actions are actually still being changed, i just cant open the /pcombo.

**Comment by Evolutious** [comment]
This may be something Dalamud is doing to combat the PvP mods that are exposing the modding community in a bad light.

**Comment by rootdarkarchon** [comment]
I did recompile the previous main build and it works fine.

CustomComboPreset:259 needs DragoonFullThrustBuffSaver to something else than 2208, then it works again.

Seems like an oversight on copypaste.

**Comment by PrincessRTFM** [comment]
Yeah, that enum was my bad. But even without changing it, my dev build is compiling fine, and after going through my code, there's no discernible _reason_ for that specific error. It's complaining that I've added a duplicate chat link handler, which is how the update message provides a clickable link. But there's only one single call to the chat link registration function in my entire project.

**Comment by rootdarkarchon** [comment]
Yeah I think that came from trying to reinstall it multiple times while it crashed before. since the issue with the ID is resolved I think this can be closed.

**Comment by Evolutious** [comment]
Just to add to this; this is still an issue with the latest updates; at least with the build still referenced in Dalamud (6.0.8144.41220)

**Comment by PrincessRTFM** [comment]
41336 is going out now, and I can confirm that it's definitely working fine for me. Try this:

1. close the game
2. open `%AppData%\XIVLauncher\installedPlugins`
3. find the plugin folder for this version
4. delete it
5. relaunch the game
6. installing the plugin fresh

**Comment by Evolutious** [comment]
Yeah i just got 41366 and it is good now. thank you! :D
